# Configuración por defecto del organizador de documentos

# Configuración de Operación
dry_run: true
default_mode: "copy"
num_threads: 6
confidence_threshold: 15

# Configuración de Análisis de Contenido
enable_content_search: true
pdf_pages_to_read: 1
xlsx_max_sheets: 3
extensions_for_content_search: [".pdf", ".docx", ".txt", ".xlsx"]

# Configuración de OCR
enable_ocr: true
ocr_languages: "spa"
scanned_pdf_threshold: 50
ocr_max_pages: 1
ocr_min_text_threshold: 30

# Configuración de Renombrado
max_filename_length: 100

# Configuración de Organización por Usuario
enable_user_organization: true

# Configuración de Cache
cache_max_size: 100
cache_ttl_seconds: 3600
min_file_size_for_cache: 1048576  # 1MB

# Configuración de Logging
verbose: false
log_file: "proceso.log"
csv_file: "resultados.csv"

# Categorías de Documentos
categories:
  "00": "00 Formato Check List"
  "01": "01 Requisición del Personal"
  "02": "02 Formato Hoja de Vida Unica"
  "03": "03 Certificados de Estudios"
  "04": "04 Certificaciones de Experiencia Laboral"
  "05": "05 certificación y Afiliación EPS"
  "06": "06 Afiliación ARL"
  "07": "07 Afiliación Caja de Compensación"
  "08": "08 Afiliación Fondo de Pensiones"
  "09": "09 Contrato de Trabajo"
  "10": "10 Documento de Identidad"
  "11": "11 Examen Médico de Ingreso"
  "12": "12 Antecedentes Disciplinarios PGN"
  "13": "13 Antecedentes Fiscales CGR"
  "14": "14 Antecedentes Judiciales PONAL"
  "15": "15 Medidas Correctivas PONAL"
  "16": "16 Certificación Bancaria"
  "17": "17 Licencia de Conducción"
  "18": "18 Tarjeta Profesional"
  "19": "19 Constancia Inducción Corporativa"
  "20": "20 Foto (png)"
  "21": "21 Autorización Tratamiento Datos Personales"
  "22": "22 Declaración de no Inhabilidad e Incompatibilidad"
  "23": "23 Otros Documentos Solicitados para el Ingreso"
  "24": "24 Examen Medico Periódico y Reubicación"
  "25": "25 Permisos"
  "27": "27 Incapacidades"
  "28": "28 Vacaciones"
  "29": "29 Encargos"
  "30": "30 Cesantías"
  "31": "31 Certificaciones Laborales"
  "32": "32 Formatos Dedución Rte Fte"
  "33": "33 Certificados Ingresos y Retenciones"
  "34": "34 Verificaciones"
  "35": "35 Reinducciones"
  "36": "36 Carnet de Vacunas"
  "37": "37 Protocolo de Retiro y documentos de retiro"
  "38": "38 Actas de Entrega"
  "39": "39 Validaciones"
  "40": "40 Procesos Disciplinarios"
  "41": "41 Otros documentos"
  "42": "42 Evaluaciones de desempeño"

# Keywords por Categoría (máximo 5 por categoría para optimizar rendimiento)
keywords:
  "00": ["check list", "lista chequeo", "formato check list", "expediente laboral", "lista de chequeo"]
  "01": ["requisicion", "solicitud personal", "requisicion personal", "formato requisicion", "solicitud empleo"]
  "02": ["hoja de vida", "cv", "curriculum", "hv", "curriculum vitae"]
  "03": ["estudios", "diploma", "acta de grado", "titulo profesional", "tecnologo"]
  "04": ["experiencia laboral", "certificaciones de experiencia laboral", "presto sus servicios", "certificaciones experiencia", "certificado experiencia"]
  "05": ["eps", "afiliacion salud", "salud eps", "afiliacion eps", "certificacion eps"]
  "06": ["afiliacion en nuestra ARL", "afiliacion en el ramo de resgos laborales", "riesgos laborales", "AFILIACION ARL", "certificado de afiliacion"]
  "07": ["caja compensacion", "ccf", "compensacion familiar", "afiliacion caja de compensacion", "afiliacion compensacion familiar"]
  "08": ["afiliacion fondo de pensiones", "fondo pension", "afiliacion pension", "fondo pensiones obligatorias", "porvenir"]
  "09": ["contrato", "contrato trabajo", "contrato laboral", "contrato individual trabajo", "termino indefinido"]
  "10": ["documento de identidad", "documento identidad", "republica de colombia", "cedula de ciudadania", "identificacion personal"]
  "11": ["examen medico", "examen ingreso", "aptitud medica", "examen medico ingreso", "certificado medico ocupacional"]
  "12": ["pgn", "procuraduria", "antecedentes disciplinarios", "certificado antecedentes", "procuraduria general nacion"]
  "13": ["cgr", "contraloria", "antecedentes fiscales", "contraloria general republica", "certificado fiscal"]
  "14": ["ponal", "policia", "antecedentes judiciales", "policia nacional", "antecedentes penales"]
  "15": ["medidas correctivas", "medidas correctivas ponal", "registro nacional medidas correctivas", "rnmc", "certificado medidas correctivas"]
  "16": ["certificacion bancaria", "cuenta bancaria", "certificado bancario", "cuenta ahorros", "cuenta corriente"]
  "17": ["licencia conduccion", "pase", "licencia conducir", "licencia transito", "pase conduccion"]
  "18": ["tarjeta profesional", "matricula profesional", "copnia", "TP", "TP profesional"]
  "19": ["induccion", "reinduccion", "induccion corporativa", "constancia induccion", "formato induccion"]
  "20": ["foto", "fotografia", "foto documento", "foto carnet", "foto 3x4"]
  "21": ["tratamiento datos", "habeas data", "autorizacion datos", "datos personales", "autorizacion tratamiento datos"]
  "22": ["inhabilidad", "incompatibilidad", "declaracion juramentada", "certificado inhabilidades", "conflicto intereses"]
  "23": ["otros ingreso", "otros documentos ingreso", "evaluacion periodo prueba", "formato evaluacion", "periodo prueba"]
  "24": ["examen periodico", "reubicacion", "examen medico periodico", "certificado medico periodico", "examen ocupacional periodico"]
  "25": ["permiso", "licencia no remunerada", "permisos", "formato control novedades", "permiso personal"]
  "27": ["incapacidad", "incapacidades", "incapacidad medica", "certificado incapacidad", "licencia medica"]
  "28": ["vacaciones", "solicitud vacaciones", "formato vacaciones", "solicitud disfrute vacaciones", "periodo vacaciones"]
  "29": ["encargo", "encargos", "encargo cargo", "encargo funciones", "delegacion funciones"]
  "30": ["cesantias", "retiro cesantias", "solicitud cesantias", "liquidacion cesantias", "certificado cesantias"]
  "31": ["certificaciones laborales", "constancias laborales", "certificado laboral", "constancia laboral", "certificacion trabajo"]
  "32": ["deduccion", "retefuente", "retencion fuente", "deduccion retefuente", "formato deduccion"]
  "33": ["ingresos y retenciones", "ingresos retenciones", "certificado ingresos", "certificado retenciones", "certificacion ingresos"]
  "34": ["verificacion", "poligrafo", "verificaciones", "verificacion titulo", "verificacion titulos"]
  "35": ["reinducciones", "reinduccion", "capacitacion recurrente", "entrenamiento periodico", "actualizacion induccion"]
  "36": ["vacunas", "carnet vacunacion", "carnet vacunas", "vacunacion", "certificado vacunas"]
  "37": ["retiro", "paz y salvo", "acta retiro", "examen egreso", "paz salvo"]
  "38": ["acta entrega", "entrega puesto", "actas entrega", "inventario entrega", "transferencia responsabilidades"]
  "39": ["validacion", "validaciones", "aprobacion", "revision formal", "validacion documentos"]
  "40": ["proceso disciplinario", "llamado atencion", "memorando", "memorando disciplinario", "sancion disciplinaria"]
  "41": ["otros", "varios", "otros documentos", "documentos varios", "miscelaneos"]
  "42": ["evaluacion desempeño", "evaluacion rendimiento", "evaluacion desempeno", "calificacion desempeño", "review desempeño"]