# Configuración de logging para el organizador de documentos

version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(threadName)s] - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "%(levelname)s - %(message)s"
  
  json:
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: proceso.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8
  
  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: errores.log
    encoding: utf8

loggers:
  organizador_documentos:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  organizador_documentos.core:
    level: DEBUG
    handlers: [file]
    propagate: true
  
  organizador_documentos.utils:
    level: INFO
    handlers: [file]
    propagate: true

root:
  level: WARNING
  handlers: [console]